export const ADD_CITY_DATA = 'ADD_CITY_DATA'
export const ADD_FB_DATA = 'ADD_FB_DATA'
export const ANIMATE_UI = 'ANIMATE_UI'
export const NULL_ACTIVE = 'NULL_ACTIVE'
export const REQUESTS = 'REQUESTS'
export const RESET_UI = 'RESET_UI'
export const SET_ACTIVE = 'SET_ACTIVE'
