export const NULL_ACTIVE = 'NULL_ACTIVE'
export const REQUEST = 'REQUEST'
export const RESET_UI = 'RESET_UI'
export const SET_ACTIVE = 'SET_ACTIVE'
export const SET_CITY = 'SET_CITY'
export const SET_GRAPH = 'SET_GRAPH'
export const TOGGLE = 'TOGGLE'
